version: '3.8'

networks:
  pvpgn-net:
    ipam:
      config:
        - subnet: 192.168.55.0/24
          gateway: 192.168.55.1

services:
  pvpgn-pro:
    image: pvpgn-pro:1.99.7.2.1
    build:
      context: .
      dockerfile: PVPGN.Dockerfile
    # docker run --rm -v $PWD/pvpgn/etc:/usr/local/pvpgn/etc pvpgn-pro:1.99.7.2.1 cp -vnpr /pvpgn/etc/pvpgn/ /usr/local/pvpgn/etc/
    # docker run --rm -v $PWD/pvpgn/var:/usr/local/pvpgn/var pvpgn-pro:1.99.7.2.1 cp -vnpr /pvpgn/var/pvpgn/ /usr/local/pvpgn/var/
    volumes:
      - $PWD/pvpgn/etc:/pvpgn/etc
      - $PWD/pvpgn/var:/pvpgn/var
    extra_hosts:
      - local:${LOCAL_IP}
  pvpgn:
    extends:
      service: pvpgn-pro
    networks:
      pvpgn-net:
        ipv4_address: 192.168.55.2
    ports:
      - 6112:6112
      - 6112:6112/udp
    entrypoint: ["bnetd","-f"]
    restart: always
  d2cs:
    extends:
      service: pvpgn-pro
    networks:
      pvpgn-net:
        ipv4_address: 192.168.55.3
    ports:
      - 6113:6113
      - 6113:6113/udp
    entrypoint: ["d2cs","-f"]
    restart: always
  d2dbs:
    extends:
      service: pvpgn-pro
    networks:
      pvpgn-net:
        ipv4_address: 192.168.55.4
    ports:
      - 6114:6114
      - 6114:6114/udp
    entrypoint: ["d2dbs","-f"]
    restart: always
  d2gs:
    build:
      context: .
      dockerfile: D2GS.Dockerfile
    ports:
      - 4000:4000
      - 4000:4000/udp
    volumes:
      - $PWD/d2gs:/D2GS/drive_c/Diablo2
    networks:
      pvpgn-net:
        ipv4_address: 192.168.55.5
    restart: always
    healthcheck:
      test: ss -tanp | grep 4000 || exit 1
      interval: 5s
      start_period: 10s
      retries: 0
