name: Build Branch

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and Push D2GS
      uses: docker/build-push-action@v3
      with:
        file: D2GS.Dockerfile
        context: .
        push: true
        tags: dschu012/d2gs:latest
    - name: Build and Push PVPGN
      uses: docker/build-push-action@v3
      with:
        file: PVPGN.Dockerfile
        context: .
        push: true
        tags: dschu012/pvpgn:latest